import { Inter } from "next/font/google";
import "./globals.css";
import TokenDataWrapper from "../app/Components/Tokenwrap"
import { Toaster } from "react-hot-toast";
import Providers from "./redux/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Admin Panel",
  description: "Generated by Grovyo",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <TokenDataWrapper>
          <Providers>
            {children}
          </Providers>
        </TokenDataWrapper>
      </body>
    </html>
  );
}
